### PR TITLE
refactor: use @grpc/grpc-js compatible packages

### PR DESCRIPTION
**Pull request by eeston**
Hey guys,

So this package relies on `grpc-create-error`, which relies on `grpc-error`, which relies on an old version of `grpc-create-metadata` and that uses the deprecated version of `grpc`.

I hope I got the order correct...  😅

You'll see I've republished a few of the non `@mali` dependencies myself as some of the PRs I raised didn't get much traction. I'm happy to push these changes back upstream though.

### CODE REVIEW

**Comment by eeston** [comment]
Temporarily closed due to a couple of failing tests. Will fix and push an update up shortly

**Comment by eeston** [comment]
Hey! Got some time to look at the tests and it seems like the status codes have changed since these tests were written. I've used this doc for reference...

https://grpc.github.io/grpc/core/md_doc_statuscodes.html

**Comment by eeston** [comment]
Hey guys. Is there any interest in keeping this up to date?

**Comment by bojand** [comment]
should be updated in 0.3.0

**Comment by eeston** [comment]
Thanks a lot! I noticed you've bumped a few other packages too. Really appreciate the effort. I had a few forked packages that were temporarily published as a stopgap. I'll deprecate them and point back to the originals 👍 If you get a moment there's just one more that requires a small update here https://github.com/bojand/grpc-error/pull/4

On a side note do you think it would worth pulling all of your Mali packages into a monorepo to make them easier to maintain? I would happily offer assistance if required.

**Pull request closed without merging**
